export var myheader = () => import("./header.vue")
export var mycarousel = () => import("./carousel.vue")
export var mymenulist = () => import("./menulist.vue")
export var myhiddennav = () => import("./hiddennav.vue")
export var myhotlist = () => import("./hotlist.vue")
